---
title: "Visual tests"
author: "David Gohel"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
require("pdftools")
require("base64")
docx_html_encode <- function( file, wd = getwd() ){
  cmd_ <- sprintf(
    "/Applications/LibreOffice.app/Contents/MacOS/soffice --headless --convert-to pdf --outdir %s %s",
    wd, file )
  system(cmd_)
  
  pdf_file <- gsub("\\.(docx|pptx)$", ".pdf", basename(file))
  pdf_file <- file.path(wd, pdf_file)
  screen_copies <- pdftools::pdf_convert(pdf = pdf_file, format = "png", verbose = FALSE)
  cat("<h3>", file, "</h3>")
  for(i in seq_along(screen_copies)){
    cat("<p>", base64::img(screen_copies[i]), "</p>")
  }
  unlink(screen_copies)
  unlink(pdf_file)
  invisible()
}
```


```{r echo=FALSE, results='asis'}
all_files <- list.files("../docs/articles/", recursive = TRUE,
   pattern = "\\.(docx|pptx)$", full.names = TRUE)
all_files <- sort(all_files)
purrr::walk(all_files, docx_html_encode)
```
