// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ppr_new
SEXP ppr_new(Rcpp::List compounds);
RcppExport SEXP oxbase_ppr_new(SEXP compoundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type compounds(compoundsSEXP);
    rcpp_result_gen = Rcpp::wrap(ppr_new(compounds));
    return rcpp_result_gen;
END_RCPP
}
// w_ppr
std::string w_ppr(std::string text_align, int pb, int pt, int pl, int pr, int shd_r, int shd_g, int shd_b, int shd_a, IntegerVector btlr_red, IntegerVector btlr_green, IntegerVector btlr_blue, IntegerVector btlr_alpha, CharacterVector type, IntegerVector width);
RcppExport SEXP oxbase_w_ppr(SEXP text_alignSEXP, SEXP pbSEXP, SEXP ptSEXP, SEXP plSEXP, SEXP prSEXP, SEXP shd_rSEXP, SEXP shd_gSEXP, SEXP shd_bSEXP, SEXP shd_aSEXP, SEXP btlr_redSEXP, SEXP btlr_greenSEXP, SEXP btlr_blueSEXP, SEXP btlr_alphaSEXP, SEXP typeSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type text_align(text_alignSEXP);
    Rcpp::traits::input_parameter< int >::type pb(pbSEXP);
    Rcpp::traits::input_parameter< int >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< int >::type pl(plSEXP);
    Rcpp::traits::input_parameter< int >::type pr(prSEXP);
    Rcpp::traits::input_parameter< int >::type shd_r(shd_rSEXP);
    Rcpp::traits::input_parameter< int >::type shd_g(shd_gSEXP);
    Rcpp::traits::input_parameter< int >::type shd_b(shd_bSEXP);
    Rcpp::traits::input_parameter< int >::type shd_a(shd_aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_red(btlr_redSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_green(btlr_greenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_blue(btlr_blueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_alpha(btlr_alphaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(w_ppr(text_align, pb, pt, pl, pr, shd_r, shd_g, shd_b, shd_a, btlr_red, btlr_green, btlr_blue, btlr_alpha, type, width));
    return rcpp_result_gen;
END_RCPP
}
// a_ppr
std::string a_ppr(std::string text_align, int pb, int pt, int pl, int pr, int shd_r, int shd_g, int shd_b, int shd_a, IntegerVector btlr_red, IntegerVector btlr_green, IntegerVector btlr_blue, IntegerVector btlr_alpha, CharacterVector type, IntegerVector width);
RcppExport SEXP oxbase_a_ppr(SEXP text_alignSEXP, SEXP pbSEXP, SEXP ptSEXP, SEXP plSEXP, SEXP prSEXP, SEXP shd_rSEXP, SEXP shd_gSEXP, SEXP shd_bSEXP, SEXP shd_aSEXP, SEXP btlr_redSEXP, SEXP btlr_greenSEXP, SEXP btlr_blueSEXP, SEXP btlr_alphaSEXP, SEXP typeSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type text_align(text_alignSEXP);
    Rcpp::traits::input_parameter< int >::type pb(pbSEXP);
    Rcpp::traits::input_parameter< int >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< int >::type pl(plSEXP);
    Rcpp::traits::input_parameter< int >::type pr(prSEXP);
    Rcpp::traits::input_parameter< int >::type shd_r(shd_rSEXP);
    Rcpp::traits::input_parameter< int >::type shd_g(shd_gSEXP);
    Rcpp::traits::input_parameter< int >::type shd_b(shd_bSEXP);
    Rcpp::traits::input_parameter< int >::type shd_a(shd_aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_red(btlr_redSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_green(btlr_greenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_blue(btlr_blueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_alpha(btlr_alphaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(a_ppr(text_align, pb, pt, pl, pr, shd_r, shd_g, shd_b, shd_a, btlr_red, btlr_green, btlr_blue, btlr_alpha, type, width));
    return rcpp_result_gen;
END_RCPP
}
// css_ppr
std::string css_ppr(std::string text_align, int pb, int pt, int pl, int pr, int shd_r, int shd_g, int shd_b, int shd_a, IntegerVector btlr_red, IntegerVector btlr_green, IntegerVector btlr_blue, IntegerVector btlr_alpha, CharacterVector type, IntegerVector width);
RcppExport SEXP oxbase_css_ppr(SEXP text_alignSEXP, SEXP pbSEXP, SEXP ptSEXP, SEXP plSEXP, SEXP prSEXP, SEXP shd_rSEXP, SEXP shd_gSEXP, SEXP shd_bSEXP, SEXP shd_aSEXP, SEXP btlr_redSEXP, SEXP btlr_greenSEXP, SEXP btlr_blueSEXP, SEXP btlr_alphaSEXP, SEXP typeSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type text_align(text_alignSEXP);
    Rcpp::traits::input_parameter< int >::type pb(pbSEXP);
    Rcpp::traits::input_parameter< int >::type pt(ptSEXP);
    Rcpp::traits::input_parameter< int >::type pl(plSEXP);
    Rcpp::traits::input_parameter< int >::type pr(prSEXP);
    Rcpp::traits::input_parameter< int >::type shd_r(shd_rSEXP);
    Rcpp::traits::input_parameter< int >::type shd_g(shd_gSEXP);
    Rcpp::traits::input_parameter< int >::type shd_b(shd_bSEXP);
    Rcpp::traits::input_parameter< int >::type shd_a(shd_aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_red(btlr_redSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_green(btlr_greenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_blue(btlr_blueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_alpha(btlr_alphaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(css_ppr(text_align, pb, pt, pl, pr, shd_r, shd_g, shd_b, shd_a, btlr_red, btlr_green, btlr_blue, btlr_alpha, type, width));
    return rcpp_result_gen;
END_RCPP
}
// rpr_new
SEXP rpr_new(Rcpp::List compounds);
RcppExport SEXP oxbase_rpr_new(SEXP compoundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type compounds(compoundsSEXP);
    rcpp_result_gen = Rcpp::wrap(rpr_new(compounds));
    return rcpp_result_gen;
END_RCPP
}
// rpr_w
std::string rpr_w(SEXP fp);
RcppExport SEXP oxbase_rpr_w(SEXP fpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fp(fpSEXP);
    rcpp_result_gen = Rcpp::wrap(rpr_w(fp));
    return rcpp_result_gen;
END_RCPP
}
// rpr_p
std::string rpr_p(SEXP fp);
RcppExport SEXP oxbase_rpr_p(SEXP fpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fp(fpSEXP);
    rcpp_result_gen = Rcpp::wrap(rpr_p(fp));
    return rcpp_result_gen;
END_RCPP
}
// rpr_css
std::string rpr_css(SEXP fp);
RcppExport SEXP oxbase_rpr_css(SEXP fpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fp(fpSEXP);
    rcpp_result_gen = Rcpp::wrap(rpr_css(fp));
    return rcpp_result_gen;
END_RCPP
}
// chunk_w
std::string chunk_w(std::string value, SEXP fp);
RcppExport SEXP oxbase_chunk_w(SEXP valueSEXP, SEXP fpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fp(fpSEXP);
    rcpp_result_gen = Rcpp::wrap(chunk_w(value, fp));
    return rcpp_result_gen;
END_RCPP
}
// chunk_p
std::string chunk_p(std::string value, SEXP fp);
RcppExport SEXP oxbase_chunk_p(SEXP valueSEXP, SEXP fpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fp(fpSEXP);
    rcpp_result_gen = Rcpp::wrap(chunk_p(value, fp));
    return rcpp_result_gen;
END_RCPP
}
// chunk_html
std::string chunk_html(std::string value, SEXP fp);
RcppExport SEXP oxbase_chunk_html(SEXP valueSEXP, SEXP fpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fp(fpSEXP);
    rcpp_result_gen = Rcpp::wrap(chunk_html(value, fp));
    return rcpp_result_gen;
END_RCPP
}
// w_tcpr
std::string w_tcpr(std::string vertical_align, std::string text_direction, int mb, int mt, int ml, int mr, int shd_r, int shd_g, int shd_b, int shd_a, bool do_bgimg, std::string bgimg_rid, std::string bgimg_path, IntegerVector btlr_red, IntegerVector btlr_green, IntegerVector btlr_blue, IntegerVector btlr_alpha, CharacterVector type, IntegerVector width, int row_span, int column_span);
RcppExport SEXP oxbase_w_tcpr(SEXP vertical_alignSEXP, SEXP text_directionSEXP, SEXP mbSEXP, SEXP mtSEXP, SEXP mlSEXP, SEXP mrSEXP, SEXP shd_rSEXP, SEXP shd_gSEXP, SEXP shd_bSEXP, SEXP shd_aSEXP, SEXP do_bgimgSEXP, SEXP bgimg_ridSEXP, SEXP bgimg_pathSEXP, SEXP btlr_redSEXP, SEXP btlr_greenSEXP, SEXP btlr_blueSEXP, SEXP btlr_alphaSEXP, SEXP typeSEXP, SEXP widthSEXP, SEXP row_spanSEXP, SEXP column_spanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type vertical_align(vertical_alignSEXP);
    Rcpp::traits::input_parameter< std::string >::type text_direction(text_directionSEXP);
    Rcpp::traits::input_parameter< int >::type mb(mbSEXP);
    Rcpp::traits::input_parameter< int >::type mt(mtSEXP);
    Rcpp::traits::input_parameter< int >::type ml(mlSEXP);
    Rcpp::traits::input_parameter< int >::type mr(mrSEXP);
    Rcpp::traits::input_parameter< int >::type shd_r(shd_rSEXP);
    Rcpp::traits::input_parameter< int >::type shd_g(shd_gSEXP);
    Rcpp::traits::input_parameter< int >::type shd_b(shd_bSEXP);
    Rcpp::traits::input_parameter< int >::type shd_a(shd_aSEXP);
    Rcpp::traits::input_parameter< bool >::type do_bgimg(do_bgimgSEXP);
    Rcpp::traits::input_parameter< std::string >::type bgimg_rid(bgimg_ridSEXP);
    Rcpp::traits::input_parameter< std::string >::type bgimg_path(bgimg_pathSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_red(btlr_redSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_green(btlr_greenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_blue(btlr_blueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_alpha(btlr_alphaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type row_span(row_spanSEXP);
    Rcpp::traits::input_parameter< int >::type column_span(column_spanSEXP);
    rcpp_result_gen = Rcpp::wrap(w_tcpr(vertical_align, text_direction, mb, mt, ml, mr, shd_r, shd_g, shd_b, shd_a, do_bgimg, bgimg_rid, bgimg_path, btlr_red, btlr_green, btlr_blue, btlr_alpha, type, width, row_span, column_span));
    return rcpp_result_gen;
END_RCPP
}
// a_tcpr
std::string a_tcpr(std::string vertical_align, std::string text_direction, int mb, int mt, int ml, int mr, int shd_r, int shd_g, int shd_b, int shd_a, bool do_bgimg, std::string bgimg_rid, std::string bgimg_path, IntegerVector btlr_red, IntegerVector btlr_green, IntegerVector btlr_blue, IntegerVector btlr_alpha, CharacterVector type, IntegerVector width, int row_span, int column_span);
RcppExport SEXP oxbase_a_tcpr(SEXP vertical_alignSEXP, SEXP text_directionSEXP, SEXP mbSEXP, SEXP mtSEXP, SEXP mlSEXP, SEXP mrSEXP, SEXP shd_rSEXP, SEXP shd_gSEXP, SEXP shd_bSEXP, SEXP shd_aSEXP, SEXP do_bgimgSEXP, SEXP bgimg_ridSEXP, SEXP bgimg_pathSEXP, SEXP btlr_redSEXP, SEXP btlr_greenSEXP, SEXP btlr_blueSEXP, SEXP btlr_alphaSEXP, SEXP typeSEXP, SEXP widthSEXP, SEXP row_spanSEXP, SEXP column_spanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type vertical_align(vertical_alignSEXP);
    Rcpp::traits::input_parameter< std::string >::type text_direction(text_directionSEXP);
    Rcpp::traits::input_parameter< int >::type mb(mbSEXP);
    Rcpp::traits::input_parameter< int >::type mt(mtSEXP);
    Rcpp::traits::input_parameter< int >::type ml(mlSEXP);
    Rcpp::traits::input_parameter< int >::type mr(mrSEXP);
    Rcpp::traits::input_parameter< int >::type shd_r(shd_rSEXP);
    Rcpp::traits::input_parameter< int >::type shd_g(shd_gSEXP);
    Rcpp::traits::input_parameter< int >::type shd_b(shd_bSEXP);
    Rcpp::traits::input_parameter< int >::type shd_a(shd_aSEXP);
    Rcpp::traits::input_parameter< bool >::type do_bgimg(do_bgimgSEXP);
    Rcpp::traits::input_parameter< std::string >::type bgimg_rid(bgimg_ridSEXP);
    Rcpp::traits::input_parameter< std::string >::type bgimg_path(bgimg_pathSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_red(btlr_redSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_green(btlr_greenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_blue(btlr_blueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_alpha(btlr_alphaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type row_span(row_spanSEXP);
    Rcpp::traits::input_parameter< int >::type column_span(column_spanSEXP);
    rcpp_result_gen = Rcpp::wrap(a_tcpr(vertical_align, text_direction, mb, mt, ml, mr, shd_r, shd_g, shd_b, shd_a, do_bgimg, bgimg_rid, bgimg_path, btlr_red, btlr_green, btlr_blue, btlr_alpha, type, width, row_span, column_span));
    return rcpp_result_gen;
END_RCPP
}
// css_tcpr
std::string css_tcpr(std::string vertical_align, std::string text_direction, int mb, int mt, int ml, int mr, int shd_r, int shd_g, int shd_b, int shd_a, bool do_bgimg, std::string bgimg_rid, std::string bgimg_path, IntegerVector btlr_red, IntegerVector btlr_green, IntegerVector btlr_blue, IntegerVector btlr_alpha, CharacterVector type, IntegerVector width, int row_span, int column_span);
RcppExport SEXP oxbase_css_tcpr(SEXP vertical_alignSEXP, SEXP text_directionSEXP, SEXP mbSEXP, SEXP mtSEXP, SEXP mlSEXP, SEXP mrSEXP, SEXP shd_rSEXP, SEXP shd_gSEXP, SEXP shd_bSEXP, SEXP shd_aSEXP, SEXP do_bgimgSEXP, SEXP bgimg_ridSEXP, SEXP bgimg_pathSEXP, SEXP btlr_redSEXP, SEXP btlr_greenSEXP, SEXP btlr_blueSEXP, SEXP btlr_alphaSEXP, SEXP typeSEXP, SEXP widthSEXP, SEXP row_spanSEXP, SEXP column_spanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type vertical_align(vertical_alignSEXP);
    Rcpp::traits::input_parameter< std::string >::type text_direction(text_directionSEXP);
    Rcpp::traits::input_parameter< int >::type mb(mbSEXP);
    Rcpp::traits::input_parameter< int >::type mt(mtSEXP);
    Rcpp::traits::input_parameter< int >::type ml(mlSEXP);
    Rcpp::traits::input_parameter< int >::type mr(mrSEXP);
    Rcpp::traits::input_parameter< int >::type shd_r(shd_rSEXP);
    Rcpp::traits::input_parameter< int >::type shd_g(shd_gSEXP);
    Rcpp::traits::input_parameter< int >::type shd_b(shd_bSEXP);
    Rcpp::traits::input_parameter< int >::type shd_a(shd_aSEXP);
    Rcpp::traits::input_parameter< bool >::type do_bgimg(do_bgimgSEXP);
    Rcpp::traits::input_parameter< std::string >::type bgimg_rid(bgimg_ridSEXP);
    Rcpp::traits::input_parameter< std::string >::type bgimg_path(bgimg_pathSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_red(btlr_redSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_green(btlr_greenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_blue(btlr_blueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type btlr_alpha(btlr_alphaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type row_span(row_spanSEXP);
    Rcpp::traits::input_parameter< int >::type column_span(column_spanSEXP);
    rcpp_result_gen = Rcpp::wrap(css_tcpr(vertical_align, text_direction, mb, mt, ml, mr, shd_r, shd_g, shd_b, shd_a, do_bgimg, bgimg_rid, bgimg_path, btlr_red, btlr_green, btlr_blue, btlr_alpha, type, width, row_span, column_span));
    return rcpp_result_gen;
END_RCPP
}
// wml_run_pic
std::string wml_run_pic(std::string src, double width, double height);
RcppExport SEXP oxbase_wml_run_pic(SEXP srcSEXP, SEXP widthSEXP, SEXP heightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type src(srcSEXP);
    Rcpp::traits::input_parameter< double >::type width(widthSEXP);
    Rcpp::traits::input_parameter< double >::type height(heightSEXP);
    rcpp_result_gen = Rcpp::wrap(wml_run_pic(src, width, height));
    return rcpp_result_gen;
END_RCPP
}
